### PR TITLE
Update of labels of fields in CommonInfo

### PR DESCRIPTION
**Pull request by sitina**
Thank you for the library! It really eases the stuff up big time. It came as a surprise though that the field names were in German (in Dajngo's /admin) and took me a while to figure out why. In order to ease the integration and development also for non-German speakers it might make sense to have it in English.

Thank you!

### CODE REVIEW

**Comment by osamamhd** [comment]
I am using this package, I hope they merge it as fast as possible.

**Comment by GitRon** [comment]
Hi guys, thanks for the feedback! I'm planning to fix it in the next couple of days.

**Comment by sitina** [comment]
Thank you, Ron!

**Comment by GitRon** [comment]
@sitina Thx for your PR but I needed to add German translation, otherwise all projects relying on the German base strings won't show mixed languages. I plan to have it up and running latest next week.

**Comment by GitRon** [comment]
Alright, guys! New version is up and running: https://pypi.org/project/ai-django-core/5.2.1/

As I said, I provided English base and German translation. If you need some localisation, feel free to create a PR 😃

**Comment by osamamhd** [comment]
Thanks...

**Pull request closed without merging**
